# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Project2'
    organization: '1909-sep30-net'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'YoutubeJam-Angular'
    cliProjectName: 'YoutubeJam-Angular'
    cliSources: '.'
    extraProperties: |
      sonar.coverage.exclusions=**/*.spec.ts
      sonar.typescript.lcov.reportPaths=$(appDir)/coverage/$(appDir)/lcov.info
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    set +e
    npm install
    npx ng  build --prod
  displayName: 'npm install and build'

- script: npx ng test --browsers ChromeHeadless --no-watch --code-coverage
  displayName: ng test

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  displayName: 'Publish code analysis'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(cb0d2e9c-c632-4eec-93d0-d1e5f9589605)'
    appType: 'webApp'
    appName: 'YoutubeJam'
    package: 'dist/youtube-jam-angular'
    deploymentMethod: runFromPackage
    